---
dist: xenial
language: python
python:
- "3.6"
- "3.7"
- "3.8"
env:
- ENGINE=docker
- ENGINE=singularity
- ENGINE=docker WITH_K8S=1
services: docker
before_install:
- ci/scripts/install-test-deps.sh
- pip install coverage
install:
- pip install cli/[dev]
- black --check --diff .
script:
- coverage run -m unittest cli/test/test_*
after_success:
- bash <(curl -s https://codecov.io/bash)
